server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**
  security:
    oauth2:
      client:
        provider:
          keycloack:
            authorization-uri: http://127.0.0.1:8180/realms/tutorial-realm/protocol/openid-connect/auth
            userinfo-uri: http://127.0.0.1:8180/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-arttribute: preferred_username
            token-uri: http://127.0.0.1:8180/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          tutorial-client: 
            provider: keycloack
            client-id: tutorial-client
            client-secret: a7ecegrSlQ6zBDh184uMZVwz2jWQtwgW
            authorization-grant-type: authorization_code
            redirect-uri: "{base-url}/login/oauth2/client/code/tutorial-client"