server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicated:
            - Path=/user/**
        - id: car-service
          uri: lb://car-service
          predicated:
            - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicated:
            - Path=/bike/**